# Generated by Django 3.1.5 on 2021-01-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('for_sale', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True)),
                ('sale_date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_compraventa.clientes')),
                ('sold_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_compraventa.articulos')),
            ],
        ),
        migrations.CreateModel(
            name='Prendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_number', models.IntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.FloatField()),
                ('capital_debt', models.FloatField()),
                ('debt', models.FloatField()),
                ('expired', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_compraventa.articulos')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_compraventa.clientes')),
            ],
        ),
    ]
